Feature/activeMQ design
Laundry-Platform/Laundry_Core pull request #1
Opened 2022-05-05 14:04 UTC by mankicho

### What's change?
- activeMQ 의존성 추가
- activeMQ 사용하기위한 기본구조 (config, consumer, producer) 세팅

### Reference and some message to reviewers
- activeMQ 설치하기
    - **Mac**
    ```
    brew install activemq
    ```
    - **Window** : https://devbada.tistory.com/27 참조

### Related Issue
- resolved: #2 
    - @S-HoChan 위 이슈 해결해서 해당 PR로 commit해주세요.

2022-05-25 15:46 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/configuration/ObjectMapperConfig.java
> +public class ObjectMapperConfig {
ObjectMapper 커스터마이징 한 게 아닌데 Config로 따로 작성할 필요가 있나요?

2022-05-25 15:58 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/configuration/ObjectMapperConfig.java
> +public class ObjectMapperConfig {
ObjectMapper Bean 하나를 위해서 클래스를 만드는게 맞을까요?
일단 이렇게 하고 나중에 Bean 추가할 때 클래스명 변경 생각해보시죠

2022-05-25 15:58 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/client/activemq/MessageConsumer.java
> +import org.springframework.jms.annotation.JmsListener;
아래 의존성 추가해주세요.
- import org.apache.activemq.Message;
- import org.springframework.jms.annotation.JmsListener;

2022-05-26 12:40 UTC, daksae98 submitted a review, later dismissed

2022-05-26 12:40 UTC, qudwnbj submitted a review, later dismissed

2022-06-03 07:24 UTC, Dokyeongyun commented
develop 브랜치 만들었으니 develop 브랜치로 PR 올려주세요.

2022-06-05 12:46 UTC, Dokyeongyun commented
target브랜치 develop으로 제가 바꿨습니당

2022-06-06 01:18 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/controller/ActiveMQTestController.java
> +  private final ObjectMapper mapper;
스프링이 알아서 Bean 찾아서 매핑하는 것 같네요 ^_^

2022-06-06 01:22 UTC, Dokyeongyun commented
activeMQ 프로세스가 실행되어있지 않을 때에도 스프링 서버는 정상적으로 실행될 수 있도록 조치가 필요할 것 같아요 @mankicho

2022-06-06 05:50 UTC, mankicho commented
> @mankicho activeMQ 프로세스가 실행되어있지 않을 때에도 스프링 서버는 정상적으로 실행될 수 있도록 조치가 필요할 것 같아요

굳 @S-HoChan 에게 이슈할당

2022-06-07 02:19 UTC, S-HoChan commented
@mankicho Window의 경우 ActiveMQ를 설치해야 하는데 버전은 어떤걸 사용해야 하나요?

2022-06-08 14:21 UTC, Dokyeongyun requested changes

2022-06-13 15:01 UTC, Dokyeongyun commented on build.gradle
> +
sourceSet은 왜 추가된건가요??

2022-06-21 08:46 UTC, Dokyeongyun submitted a review, later dismissed

2022-07-20 16:50 UTC, Dokyeongyun approved these changes

2022-07-20 16:51 UTC, merged