Create File Related to Community Domain
Laundry-Platform/Laundry_Core pull request #17
Opened 2022-06-12 05:11 UTC by S-HoChan

2022-06-12 05:48 UTC, Dokyeongyun commented
@S-HoChan 
PR 올린 Branch명과 해당 PR에서 작업한 내용이 일치하지 않는데, 이 PR에서 추가적으로 작업할건가요?

2022-06-12 05:49 UTC, S-HoChan commented
> @S-HoChan PR 올린 Branch명과 해당 PR에서 작업한 내용이 일치하지 않는데, 이 PR에서 추가적으로 작업할건가요?
지금은 파일만 추가된 상태고 이후 작업을 수행할 예정입니다

2022-06-12 06:01 UTC, Dokyeongyun commented
> > @Dokyeongyun  PR 올린 Branch명과 해당 PR에서 작업한 내용이 일치하지 않는데, 이 PR에서 추가적으로 작업할건가요?
> > 지금은 파일만 추가된 상태고 이후 작업을 수행할 예정입니다

그러면 새로 추가한 developing label을 붙여주세요~~

2022-06-12 06:07 UTC, Dokyeongyun commented
@S-HoChan 
개인적으로 commit이 너무 많이 분할된 느낌인데, 하나의 작업단위를 잘 설정하는 것이 좋을 것 같아요
아래 세 개의 commit은 "커뮤니티 관련 mvc 구조 추가" 정도의 commit message로 해서 하나로 합쳐지면 좋을 것 같습니다.
- f3762c295ada3232497b3304fe5a5872bcee9acf
- dcb16800c4cb7c605651e4f20a03ed3cf6f09a08
- 7f2e6bed52cfb98ab0c0d59015ffe75c5e8e55ec

2022-06-13 13:26 UTC, mankicho reviewed
구조 완성했으면 테스트코드도 같이 작성 하면좋을듯

더미데이터 생성해놓고, 잘 CRUD 되는지

2022-06-14 08:53 UTC, S-HoChan commented on src/main/java/com/coders/laundry/controller/BoardController.java
> +    @Autowired
생성자 인젝션으로 수정하였습니다.

2022-06-15 07:42 UTC, Dokyeongyun requested changes
테스트코드는 급하지 않으니 천천히 확인해보면 될 것 같고,
서비스 계층의 행위, 역할에 대해 고민해보면 좋을 것 같아요

2022-06-15 07:42 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/controller/BoardController.java
> +    }
우리는 Lombok 라이브러리를 사용하고 있으니, 
해당 생성자는 @RequiredArgsConstructor 또는 @AllArgsConstructor 를 사용하는 편이 좋을 것 같아요.

- **Reference**
    - https://dingue.tistory.com/14

2022-06-15 07:42 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/service/BoardService.java
> +    }
@RequiredArgsConstructor를 사용하지 않은 이유가 있나요?

2022-06-15 07:42 UTC, Dokyeongyun commented on src/main/resources/db/h2/dev/schema.sql
> +        delete_date DATE
두 컬럼은 DATETIME으로 변경하는 것이 어떨까요?
다른 테이블의 동일이름의 컬럼도!
- **Reference**
    - https://m.blog.naver.com/nieah914/221810697040

2022-06-15 07:42 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/service/BoardService.java
> +    }
Repository에서 조회한 데이터를 그대로 반환하는게 Service의 목적인가요?
해당 Service의 행위를 결정하고 그 행위에 따라 메서드를 작성하는 게 좋을 것 같습니다.
Service의 행위, 역할이 결정된다면 네이밍도 그에 따라 변경해주면 좋을 것 같아요.

2022-06-15 07:42 UTC, Dokyeongyun commented on src/test/java/com/coders/laundry/service/BoardServiceTest.java
> +}
- 해당 테스트 메서드에서는 어떤 것을 테스트하려는 건지 모르겠어요
- 테스트의 단위는 실제 Service 클래스에 작성된 메서드 단위로 하면 좋을 것 같아요.
- AAA 패턴 또는 given-when-then 패턴을 사용해서 테스트합시다. (동일한 개념)
    - Arrange : 테스트에 필요한 데이터를 생성하고 Mock객체의 행위를 Mocking한다.
    - Act : 실제 테스트하려는 메서드를 실행한다.
    - Assert : Act의 결과를 검증한다.

2022-06-15 07:46 UTC, Dokyeongyun commented
- 이 커밋에서 많은 작업이 이루어졌는데 커밋 메시지가 해당 커밋의 작업내용을 표현하지 못하는 것 같습니다
    - 0fdaee17f5073517c6fbb194c139f7a9458a6d28
    - [쿼리작성 + Repository에서 조회 + 잘 조회되는지 확인하는 테스트]를 하나의 단위로 하는 것이 좋을 것 같아요

2022-06-15 07:53 UTC, S-HoChan commented on src/main/resources/db/h2/dev/schema.sql
> +        delete_date DATE
update_date의 경우는 다시 생각해보니 DATETIME이 맞는것 같습니다. delete_date의 경우 시, 분, 초까지 저장해야 할 이유가 따로 있을까요?

2022-06-15 08:27 UTC, Dokyeongyun commented on src/main/resources/db/h2/dev/schema.sql
> +        delete_date DATE
처음에 `delete_date`컬럼을 추가한 이유가 뭔가요??
`update_date`, `delete_date` 컬럼을 이용해서 하고자 하는 것이 뭔지를 먼저 얘기해봐야 할 것 같아요
단순히 수정, 삭제 여부만 알고 싶은거라면 굳이 4~8 Byte를 차지하는 `DATE`, `DATETIME`을 사용하는 것보다 `BOOLEAN`을 사용해도 될 것 같습니다.

2022-06-15 08:32 UTC, S-HoChan commented on src/main/resources/db/h2/dev/schema.sql
> +        delete_date DATE
member 도메인에 탈퇴날짜가 있는것과 동일한 역할입니다.

2022-06-15 09:01 UTC, Dokyeongyun commented on src/main/resources/db/h2/dev/schema.sql
> +        delete_date DATE
`member` 테이블의 탈퇴일시는 개인정보보호법을 준수해야해서 필요합니당
![image](https://user-images.githubusercontent.com/61186671/173788005-a5859444-c989-4172-9d6d-535bc71b83fe.png)

2022-06-16 06:33 UTC, S-HoChan commented on src/main/java/com/coders/laundry/service/BoardService.java
> +    }
final변수와 충돌을 일으킵니다.

2022-06-16 06:34 UTC, S-HoChan commented on src/main/resources/db/h2/dev/schema.sql
> +        delete_date DATE
delete_date는 제거하겠습니다.

2022-06-19 11:51 UTC, mankicho commented on src/main/java/com/coders/laundry/controller/BoardController.java
> +    }
RequiredArgsConstructor 사용하면 final 변수에 대해서도 초기화가 가능한걸로 알고있는데 아닌가요

2022-06-19 11:51 UTC, mankicho commented on src/main/java/com/coders/laundry/controller/BoardController.java
> +    public String board(Model model) {
client 에 데이터를 json 형식으로 응답해줘야하지 않을까요

2022-06-19 11:51 UTC, mankicho commented on src/main/java/com/coders/laundry/service/BoardService.java
> +    }
생성자 지우고 RequiredArgs 어노테이션을 붙여보세요

2022-06-19 11:51 UTC, mankicho commented on src/main/java/com/coders/laundry/dto/CommentDTO.java
> +    private CommentDTO commentDTO;
CommentEntity 를 갖고있어야하지않을지

2022-06-21 12:02 UTC, Dokyeongyun approved these changes

2022-06-21 12:06 UTC, dldmldlsy approved these changes

2022-06-21 12:06 UTC, merged