add sample data to h2
Laundry-Platform/Laundry_Core pull request #28
Opened 2022-06-19 16:21 UTC by mankicho

샘플 빨래방 데이터를 h2 데이터베이스에 넣어주는 코드, 

각자 로컬환경에서 데이터 활용할수있도록 서버 시작시 데이터 넣어주도록 작성하였음.

2022-06-19 16:40 UTC, S-HoChan approved these changes

2022-06-21 04:45 UTC, Dokyeongyun commented
- 작업 시작 전에, Issue를 먼저 올려주세요..
- PR 템플릿이 아직 적용이 안됐는데, 다른 PR 참고해서 템플릿대로 작성 부탁드립니다

2022-06-21 05:18 UTC, Dokyeongyun commented
- 아래 에러 발생하는데, 이에 대한 처리가 필요할 것 같아요
![image](https://user-images.githubusercontent.com/61186671/174721580-e25c2f26-7b23-446d-b554-d6e8dc63fead.png)

2022-06-21 06:52 UTC, Dokyeongyun requested changes

2022-06-21 06:52 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/LaundryApplication.java
>      }
- main 메서드에서 객체 생성 후 메서드 호출을 하는 것보단 스프링 컨테이너 내부에서 관리될 수 있도록 Bean으로 등록하는건 어떨까요?

2022-06-21 06:52 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/data/DataCreator.java
> +    BufferedReader br2 = new BufferedReader(new FileReader(file2));
FIleReader를 사용하면 인코딩 방식 지정이 불가해서 Stream을 사용해 UTF-8로 인코딩할 수 있도록 해야할 것 같습니다.

2022-06-21 06:52 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/data/DataCreator.java
> +  private final ObjectMapper mapper = new ObjectMapper();
- @RequredArgsConstructor 어노테이션을 부여하고
- ObjectMapper를 직접 생성하지 않고 스프링 컨테이너에 등록되어 있는 ObjectMapper를 사용하면 되지 않을까요?

2022-06-21 06:52 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/data/DataCreator.java
> +     PreparedStatement statement = con.prepareStatement(query);
Connection을 직접 생성하지 않고 Repository 의존성을 주입받아서 사용하는 쪽으로 변경하겠습니다

2022-06-21 06:52 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/data/DataCreator.java
> +       statement.setBoolean(6, true);
기본값은 false예요

2022-06-21 06:52 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/util/StringUtils.java
> +}
저희는 Java 17.0.2를 사용하고 제가 알기로 이미 Java 9부터 isBlank, isEmpty 메서드를 제공하는데 굳이 이 Util을 추가할 이유는 없어보여요.

2022-06-21 06:52 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/jackson/StringLowerCaseDeserializer.java
> +        }
스프링부트에 포함된 Jackson라이브러리에서 해당 구문을 대체할 기능을 제공하니 
jackson-guava 의존성을 제거하고 jackson라이브러리의 기능을 이용해 deserialize하면 될 것 같아요

2022-06-21 11:20 UTC, Dokyeongyun approved these changes

2022-06-21 11:20 UTC, merged