Feature/login api
Laundry-Platform/Laundry_Core pull request #69
Opened 2022-07-19 09:57 UTC by dldmldlsy

### What's Changed?
- 로그인 기능 구현

### Related Issue
- 해당 PR와 관련된 Issue를 Link해주세요.
- resolved: #63 

### To reviewers

2022-07-19 13:16 UTC, Dokyeongyun requested changes
- **PR을 올리기 전, develop 브랜치의 변경사항을 merge해주세요.**
비즈니스 로직적으로 충돌되는 부분이 전혀 없다면 문제가 되지 않을 수 있겠지만, 이번 PR같은 경우는 기존 develop 브랜치의 `TokenManagerService`가 있음에도 불구하고 `TokenService`가 추가되어 추가적인 작업이 필요해집니다.
- **API가 정상 동작하는지 확인해주세요.**
postman, curl 등의 API 테스트 도구를 이용해서 개발된 API가 정상적인 응답을 반환하는지 테스트가 필요합니다. 
- **전체적으로 주석이 너무 많은 것 같아요.** 
너무 많은 주석은 가독성을 해치기도 하고, 주석 또한 지속적으로 관리해야 할 대상이기 때문에 복잡한 로직이 아니라면 주석은 최소화하는 것이 좋을 것 같습니다.
- **전반적으로 네이밍 규칙이 보완되어야 할 것 같습니다.**
snake_case가 사용된 부분이라던가, 반환값이 boolean 타입인 메서드 네이밍, 줄임말 등의 네이밍을 보다 가독성 있고 명확한 방향으로 보완되면 좋을 것 같습니다.
- **코드간 적절히 라인을 띄워주는 게 좋을 것 같아요.**
이것 또한 가독성의 문제인데, 로직을 잘 이해할 수 있도록 적절한 단위로 한 줄씩 띄워주면 좋을 것 같아요.
- **생성자 기반 의존성 주입**
생성자 기반 의존성 주입 방식을 이용하려는 것은 알겠으나, 의존성 주입되어야 할 필드를 final로 선언하고 Lombok 라이브러리의 `@RequiredArgsConstructor`를 부여하면 보다 효과적으로 가능할 것 같습니다.
- **스프링에게 생성한 객체를 알려주세요.**
`@RestController`, `@Service`, `@Repository`, `@Component` 등의 어노테이션을 적절히 사용해서 스프링 컨테이너가 이 객체들을 관리할 수 있도록 해주세요.

2022-07-23 13:15 UTC, mankicho commented on src/main/java/com/coders/laundry/dto/LoginRequest.java
> +}
추가로 password 에 대한 validate 를 model 에서 수행하도록 작성해주면좋을듯
예를들어 
@Min(length : 8) (최소길이는 8)
@Notnull

비밀번호에 특수문자가 포함되어야한다 라면 Pattern 을 도입할수도있을거같구요 
javax 의 validate 를 참조해보면 좋을거같네요
https://medium.com/@gaemi/java-%EC%99%80-spring-%EC%9D%98-validation-b5191a113f5c

2022-07-23 13:15 UTC, mankicho commented on src/main/java/com/coders/laundry/service/TokenService.java
> +    private final long tokenValidTime = 1000L*60*60*24; //토큰 만료기간 24시간으로 설정
첨언하자면, 채널톡에선 API 통신에서 사용되는 토큰은 만료기한을 짧게하고, refresh 토큰의 만료를 좀더 길게 유지하는 방식을 사용합니다. 

API 통신에 사용되는 토큰이 만료되면, Refresh 토큰을 이용해 새로운 토큰을 발급받는 방식이에요

https://velog.io/@park2348190/JWT%EC%97%90%EC%84%9C-Refresh-Token%EC%9D%80-%EC%99%9C-%ED%95%84%EC%9A%94%ED%95%9C%EA%B0%80

요거읽어보고 한번 고민해보시면 좋을듯

2022-07-23 13:18 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/controller/LoginController.java
> +    @Autowired
Good guide

2022-07-23 13:20 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/dto/LoginRequest.java
> +}
와 몰랐던 사실이네요 굿

2022-07-23 13:21 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/dto/LoginRequest.java
> +}
validation은 다른 PR에서 먼저 작업하고 올릴테니 그 후에 수정 부탁드려요

2022-07-26 17:37 UTC, dldmldlsy commented on src/main/java/com/coders/laundry/controller/LoginController.java
> +    LoginController(LoginService loginService){
그럼 @RequiredArgsConstructor를 안쓰고 생성자주입을 할 경우에는 원래 어떻게 해야하나요??

2022-07-26 17:41 UTC, dldmldlsy commented on src/main/java/com/coders/laundry/controller/LoginController.java
> +        //DB에 있는지 확인.
주석도 관리 대상이니까 복잡하지 않은 내용이라면 아예 안써서 관리할 대상을 줄이는 게 좋다는 건가용??

2022-07-26 17:41 UTC, dldmldlsy commented on src/main/java/com/coders/laundry/controller/LoginController.java
> +        //DB에 있는지 확인.
주석도 관리 대상이니까 복잡하지 않은 내용이라면 아예 안써서 관리할 대상을 줄이는 게 좋다는 건가용??

2022-07-26 17:45 UTC, dldmldlsy commented on src/main/java/com/coders/laundry/dto/LoginResponse.java
> +}
오 후자는 고민했었는데 전자는 생각못했네용 넵!+!

2022-07-26 17:48 UTC, dldmldlsy commented on src/main/java/com/coders/laundry/repository/MemberRepository.java
>      MemberEntity selectById(int memberId);
네에~~~~~~! 저는 따닥따닥 붙여써서 전체 양이 적은 게 더 잘 읽히는 편이라 자꾸 이렇게 쓰게되네요!!!!!!!!!!!!!!! 앞으로 주의해야겠어요ㅠ-ㅠ

2022-07-26 17:48 UTC, dldmldlsy commented on src/main/java/com/coders/laundry/service/LoginService.java
> +public class LoginService {
왜 그랬는지 이해가 안가영

2022-07-26 17:49 UTC, dldmldlsy commented on src/main/java/com/coders/laundry/service/LoginService.java
> +    }
덕분에 좋은 거 배웠숩니당 감사합니다~!

2022-07-26 17:49 UTC, dldmldlsy commented on src/main/java/com/coders/laundry/service/LoginService.java
> +    //회원존재여부확인
아하 몰랐어용 감사합니다~!

2022-07-26 17:50 UTC, dldmldlsy commented on src/main/java/com/coders/laundry/service/LoginService.java
> +            return true;
왕

2022-07-26 17:50 UTC, dldmldlsy commented on src/main/java/com/coders/laundry/service/LoginService.java
> +    public boolean matchPW(String phoneNum, String pw){
이거 넘 고민했는데!! 혹시 네이밍 관련 문서 있을까여

2022-07-26 17:51 UTC, dldmldlsy commented on src/main/java/com/coders/laundry/service/LoginService.java
> +        MemberEntity login_member = memberRepository.selectByPhoneNumber(phoneNum);
저도 이해가 안가영 ㅠ-ㅠ

2022-07-26 17:52 UTC, dldmldlsy commented on src/main/java/com/coders/laundry/service/LoginService.java
> +                .memberEntity(member)
아아 클라이언트에 전송할 멤버dto를 따로 만들어야한다는 걸 놓쳤네여

2022-07-26 17:54 UTC, dldmldlsy commented on src/main/java/com/coders/laundry/service/LoginService.java
> +}
혹시 다른 일에 쓰일 수도 있으니까 따로 하는 게 좋다고 생각했는데 어쩔 때 통합해야하고 어쩔 때는 나중을 위해 따로 두는 게 좋은 건지 잘 모르겠어용. 이런 경우에는 후자를 고ㄹㅕ안하나..

2022-07-26 17:55 UTC, dldmldlsy commented on src/main/java/com/coders/laundry/service/TokenService.java
> +public class TokenService {
이거 pull 했는데 반영이 안되길래 필요한대로 적어서 올렸어용 ! merge까지 해야 반영이 되는 건줄 몰랐네여

2022-07-26 17:57 UTC, dldmldlsy commented on src/main/java/com/coders/laundry/service/TokenService.java
> +    private final long tokenValidTime = 1000L*60*60*24; //토큰 만료기간 24시간으로 설정
앗 그렇게 공부는 했는데 짧고 길고의 기준을 모르겠어서 우선 하루로 했습니다..! 참고자료 읽고 수정할게용

2022-07-26 17:59 UTC, dldmldlsy commented on src/main/java/com/coders/laundry/service/TokenService.java
> +        return newToken;
저는 위에가 더 깔끔해서 그렇게 적은 거였는데 왜 inline으로 작성하는 것이 더 좋을까요? 
굳이 불필요한 newToken이라는 변수를 만들어서,,??

2022-07-26 20:37 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/controller/LoginController.java
> +        //DB에 있는지 확인.
넹 그렇습니다

2022-07-26 20:39 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/service/LoginService.java
> +public class LoginService {
실제로 테스트를 해보면 이런 실수는 없을거예요!-!

2022-07-26 20:43 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/service/LoginService.java
> +}
재사용을 위해 분리하는 방법도 좋을 수 있지만 이 경우는 db 커넥션이 발생하는 작업이라 비용이 커서 합치는 게 좋다고 생각해요. 나중에 필요할 메서드들이라면 그대로 두고 새로운 메서드를 만들어도 될 것 같습니다

2022-07-26 20:48 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/service/LoginService.java
> +    public boolean matchPW(String phoneNum, String pw){
음 갓구글에 java ~~naming을 검색하면 엄청난 문서들이 쏟아질것 같아요. 네이밍이 고민될때는 명확성, 가독성, 문맥성(?)등을 고려하면 좋습니다. 네이밍뿐만 아니라 대부분의 사람들이 보기 좋은 코드 컨벤션은 클린코드라는 책을 보면 좋을 것 같아요

2022-07-26 20:49 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/service/TokenService.java
> +    private final long tokenValidTime = 1000L*60*60*24; //토큰 만료기간 24시간으로 설정
일단은 개선이 필요할 것 같다고 리뷰한거고, 지금 수정되지는 않아도 될 것 같아요!~~ 정책적인 부분이라 같이 고민해봐도 좋을 것 같네요

2022-07-26 21:04 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/service/TokenService.java
> +        return newToken;
메서드명이 `createToken`으로 반환값이 새로운 토큰값이란 것을 기대할 수 있고 이름이 부여된 변수가 아래에서 다시 사용되지 않아서 바로 반환해줘도 될 것 같다고 생각해요~~

2022-07-27 05:07 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/service/TokenService.java
> +public class TokenService {
기본값으로 pull하면 merge까지 되도록 설정되어 있을걸요??

2022-07-27 05:09 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/controller/LoginController.java
> +    LoginController(LoginService loginService){
저렇게 하면 생성자 주입이 되긴하지만, final로 선언하지 않았기 때문에 `LoginService` 객체가 언제든지 변경될 수 있어요.
`LoginService`는 스프링 컨테이너에서 관리되는 싱글톤 빈이기 때문에 변경되면 안되겠죠?

2022-08-21 05:34 UTC, mankicho commented on src/main/java/com/coders/laundry/service/LoginService.java
> +        Member memberInfo = Member.builder()
Member 를 그대로 새로 생성하는거같은데 그러면 바로 member 를 넘겨줘도되지않을까요?

2022-08-21 05:34 UTC, mankicho commented on src/main/java/com/coders/laundry/service/LoginService.java
> +                .accessToken(tokenManagerService.createToken(member.getMemberId()))
토큰 발급이 실패하면 어떻게되나요? 트랜잭셔널 하게 처리되나요??

2022-08-22 17:48 UTC, Dokyeongyun requested changes
- Repository 계층의 테스트에는 `@Transactional` 부여하기
- PR올리기 전 gradle `test` 태스크 실행하여 성공하는 지 확인하기

2022-08-22 17:48 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/service/TokenManagerService.java
>   */
주석은 나중에 지워주세요~

2022-08-22 17:48 UTC, Dokyeongyun commented on src/main/java/com/coders/laundry/service/TokenManagerService.java
> +
- 날짜/시간과 관련된 내용을 다룰 때에는 `java.util` 패키지의 `Date`, `Calendar` 등을 사용하는 것보다 Java 8부터 지원되는 `java.time` 패키지의 `LocalDateTime`, `LocalDate` 등을 사용하는 것이 좋아요.
- 아래 글 읽어보고 나중에 바꿔보도록 합시당
  - https://d2.naver.com/helloworld/645609

2022-08-22 17:48 UTC, Dokyeongyun commented on src/test/java/com/coders/laundry/controller/LoginControllerTest.java
> +@SpringBootTest
- `@SpringBootTest` 어노테이션을 부여하게 되면 모든 스프링 Context가 구성되고 나서 해당 테스트를 실행하게 돼요. 우리는 `LoginController`와 관련된 내용들만 구성하여 테스트하면 되는데 모든 Context를 불러오게 되면 규모가 커질수록 테스트 비용이 많이 들겠죠? 
- 테스트에 필요한 최소한의 Context만 구성하는 것이 좋고, 특히 여기서는 `LoginController`의 단위 테스트를 수행하기 때문에 `Controller` 계층의 **Slice test**를 하면 될 것 같아요.

2022-08-22 17:48 UTC, Dokyeongyun commented on src/test/java/com/coders/laundry/controller/LoginControllerTest.java
> +    }
- `Controller`의 역할은 HTTP 요청을 수신하고 요청에 담긴 정보들을 검증 및 deserialize하는 것인데, 이러한 형태의 테스트에서는 이를 제대로 검증해줄 수가 없어요.
- 핸들러 메서드에 직접적으로 매개변수를 전달하여 사용하는 것은 적절하지 않고, 애초에 그런 역할도 아니기 때문에 `MockMvc`라는 객체를 이용해서 위에서 언급했던 **Slice test**를 수행하면 좋을 것 같아요.
  - https://tecoble.techcourse.co.kr/post/2021-05-18-slice-test/

2022-08-22 17:48 UTC, Dokyeongyun commented on src/test/java/com/coders/laundry/controller/LoginControllerTest.java
> +        LoginRequest loginRequest = LoginRequest.builder()
- `LoginRequest.builder()`는 컴파일이 안되네요
- `LoginRequest`에 Builder가 있는지 확인해야 할 것 같아요

2022-08-22 17:48 UTC, Dokyeongyun commented on src/test/java/com/coders/laundry/service/LoginServiceTest.java
> +    }
- 테스트 도중 앞선 Assert문이 실패하는 경우 다른 테스트는 실행조자 되지 않고 종료되기 때문에 테스트 메서드 하나에서 Act는 단 한번만 수행하는 것이 좋을 것 같아요.
- 이 경우, 아래와 같은 이름으로 적당하게 메서드를 나누어 작성하면 될 것 같아요
  - `login`
  - `login_MemberNotFound`
  - `login_InvalidPassword`
- 그리고 로그인 실패 시 `null`을 반환하는 것보다는 예외를 발생시켜 일관적인 처리를 하거나 `boolean` 값을 전달해주는 게 좋을 것 같아요. 
- `null`값을 다루는 것은 생각보다 관리하기 힘든 문제가 될 수 있을 것 같아요.

2022-08-22 17:48 UTC, Dokyeongyun commented on src/test/java/com/coders/laundry/repository/MemberRepositoryTest.java
> +    @Test
- 이 테스트 메서드만 실행하면 성공하지만 해당 클래스의 전체 테스트를 실행하면 실패해요.
  ```java
  ### Error updating database.  Cause: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "public.CONSTRAINT_INDEX_B ON public.member(phone_num NULLS FIRST) VALUES ( /* 8 */ CAST('12341234' AS CHAR(8)) )"; SQL statement:
  INSERT INTO member (phone_num, password, nickname, birthday, gender)
          VALUES (?, ?, ?, ?, ?) [23505-212]
  ```
- 위에서 Insert 했던 회원과 휴대폰 번호가 동일해서 Unique 제약조건에 따라 에러가 발생하는데, `Repository` 계층의 각 테스트에서는 `@Transactional`을 부여하여 `@Test`별로 독립적인 테스트가 이루어질 수 있도록 합시다.

2022-08-22 18:56 UTC, Dokyeongyun submitted a review, later dismissed
수고했슴다~
남은 conversation 확인 및 의견 정리 완료되었으면 resolve 해주세요.

2022-09-06 10:29 UTC, Dokyeongyun approved these changes

2022-09-06 12:51 UTC, merged